version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /Users/rafaribe/experiment-removeme/nginx-cotx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/rafaribe/experiment-removeme/nginx-cotx/ssl:/etc/ssl/

    command: [nginx-debug, "-g", "daemon off;"]
